// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlccoxrsjdgxcfenesci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsY2NveHJzamRneGNmZW5lc2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTY3NTUsImV4cCI6MjA2MzczMjc1NX0.OC-UtequANb7p0LlxNzR2qyailBSTd7Lg3RHee9YOZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);